Added German translation
dewiniaid/TimeControl pull request #1
Opened 2018-07-10 16:45 UTC by mrbesen

2018-10-08 06:40 UTC, SuperSandro2000 requested changes
I would like to see some more changes.

2018-10-08 06:40 UTC, SuperSandro2000 commented on locale/de/locale.cfg
> +gui-speed-normal=Time Warp: disabled
I would translate disabled too. How do you like ausgeschalten? Or aus?

2018-10-08 06:40 UTC, SuperSandro2000 commented on locale/de/locale.cfg
> +speed-changed-by=__2__ Hat die Geschwindigkeit auf __1__x gesetzt.
Should hat be lowercased?

2018-10-09 00:41 UTC, dewiniaid commented
Closing in favor of #2

2018-10-09 00:41 UTC, closed without merging